# Generated by Django 3.1.5 on 2021-01-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('personNumber', models.IntegerField(verbose_name='Номер телефона')),
                ('tableNumber', models.IntegerField(verbose_name='Номер столика')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('reservationTime', models.TimeField(verbose_name='Время бронирования')),
            ],
        ),
    ]
