# Generated by Django 3.1.5 on 2021-01-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablereservation',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Забронированные столы'},
        ),
        migrations.RemoveField(
            model_name='tablereservation',
            name='personNumber',
        ),
        migrations.RemoveField(
            model_name='tablereservation',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='email',
            field=models.EmailField(default='wwwwwwww@mail.ru', max_length=254, verbose_name='Ваша почта'),
        ),
    ]
