# Generated by Django 3.1.5 on 2021-01-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210128_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablereservation',
            options={'verbose_name': 'Бронрование', 'verbose_name_plural': 'Забронированные столы'},
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='email',
            field=models.EmailField(default='hsanys2000@mail.ru', max_length=254, verbose_name='Ваша почта'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='reservationTime',
            field=models.TimeField(verbose_name='Время'),
        ),
    ]
